name: just_google_signin
description:  A Google SignIn library for Dart with an OpenID Connect support.
version: 0.1.0
author: Tomas Szabo <tomas.szabo@deftomat.com>
homepage:  https://github.com/deftomat/JustGoogleSignIn

environment:
  sdk: '>=1.16.0 <2.0.0'

dependencies:
  js: '^0.6.0'

dev_dependencies:
  test: '^0.12.15'
